In [4]:
import pandas as pd
import numpy as np

In [5]:
#6
df=pd.read_csv("train.csv")
dff=df.copy()
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [6]:
#7
n=int(input("Введите число строк"))
print(df.head(n))

Введите число строк5
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [7]:
#8
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [8]:
#9
print("Количество строк:",df.shape[0])
print("Количество столбцов:",df.shape[1])

Количество строк: 891
Количество столбцов: 12

In [9]:
#10
print(df.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [10]:
#11
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
#12
numeric_features = ["Age", "SibSp", "Parch", "Fare","PassengerId"]
categorical_features = ["Survived", "Pclass", "Sex", "Embarked"]
text_features = ["Name", "Ticket", "Cabin"]
print("Количественные признаки:", numeric_features)
print("Категориальные признаки:", categorical_features)
print("Текстовые признаки:", text_features)

Количественные признаки: ['Age', 'SibSp', 'Parch', 'Fare', 'PassengerId']
Категориальные признаки: ['Survived', 'Pclass', 'Sex', 'Embarked']
Текстовые признаки: ['Name', 'Ticket', 'Cabin']

In [12]:
#13
columns = ["Age", "SibSp", "Parch", "Fare"]
statistics = pd.DataFrame({
    "Среднее": df[columns].mean(),
    "Медиана": df[columns].median(),
    "Минимум": df[columns].min(),
    "Максимум": df[columns].max(),
    "Стандартное отклонение": df[columns].std()
})
statistics

         Среднее  Медиана  Минимум  Максимум  Стандартное отклонение
Age    29.699118  28.0000     0.42   80.0000               14.526497
SibSp   0.523008   0.0000     0.00    8.0000                1.102743
Parch   0.381594   0.0000     0.00    6.0000                0.806057
Fare   32.204208  14.4542     0.00  512.3292               49.693429

In [13]:
#14
passenger_classes = df["Pclass"]
class_counts = passenger_classes.value_counts()
print(class_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [14]:
#15
un=df['Embarked'].nunique()
print(un)

3

Контрольный вопрос: Почему Pclass, содержащий целые числа, следует рассматривать как категориальный
признак?
Ответ: Так как чиса 1,2 и 3 обозначают классы обслуживания

In [15]:
#16
miss=df.isna().sum()
print(miss)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [16]:
#17
missing_percent = df.isna().mean() * 100
print(missing_percent)

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [17]:
#18
missing_counts = df.isna().sum()
column = missing_counts.idxmax()
print(column)

Cabin

In [18]:
#19
stat_before=pd.DataFrame([{
    "Среднее": df["Age"].mean(),
    "Медиана": df["Age"].median(),
    "Минимум": df["Age"].min(),
    "Максимум": df["Age"].max(),
    "Стандартное отклонение": df["Age"].std(),
    "Количество значений": df['Age'].count(),
}])
stat_before

,Среднее,Медиана,Минимум,Максимум,Стандартное отклонение,Количество значений
0,29.699118,28.0,0.42,80.0,14.526497,714

In [19]:
#20
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [20]:
#21
stat_after=pd.DataFrame([{
    "Среднее": df["Age"].mean(),
    "Медиана": df["Age"].median(),
    "Минимум": df["Age"].min(),
    "Максимум": df["Age"].max(),
    "Стандартное отклонение": df["Age"].std(),
    "Количество значений": df['Age'].count(),
}])

stat_after

,Среднее,Медиана,Минимум,Максимум,Стандартное отклонение,Количество значений
0,29.361582,28.0,0.42,80.0,13.019697,891

In [21]:
#22
srav = pd.DataFrame({
    "До заполнения": stat_before.iloc[0],
    "После заполнения": stat_after.iloc[0]
})
srav

                        До заполнения  После заполнения
Среднее                     29.699118         29.361582
Медиана                     28.000000         28.000000
Минимум                      0.420000          0.420000
Максимум                    80.000000         80.000000
Стандартное отклонение      14.526497         13.019697
Количество значений        714.000000        891.000000

In [22]:
#23
df = df.dropna(subset=["Embarked"])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [23]:
#24
missing_cabin = df['Cabin'].isna().mean()
if missing_cabin>0.5:
  df = df.drop(columns = ['Cabin'])

In [24]:
#25
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [25]:
#26
pd.DataFrame({
    "До обработки": dff.shape,
    "После обработки": df.shape,
})

   До обработки  После обработки
0           891              889
1            12               11

27. Почему медиана может быть предпочтительнее среднего?
Медиана меньше зависит от крайних значений и выбросов, поэтому может лучше отражать типичное значение.
28. Какие характеристики изменились?
После заполнения возраста изменились среднее, стандартное отклонение и количество непустых значений. Медиана, минимум и максимум сохранились.
29. Почему изменилось стандартное отклонение?
Добавление значений, равных медиане, увеличило количество наблюдений в центре распределения. В данном наборе это уменьшило разброс возрастов.
30. Сохраняется ли исходное распределение возрастов?
Нет. Возникает искусственное скопление значений в точке медианы. Неизвестные фактические возраста заменяются одной оценкой.

In [26]:
#31
survived = df['Survived'].to_numpy()
print(np.mean(survived)*100)

38.24521934758155

In [27]:
#32
sex = df['Sex'].to_numpy()
male=np.mean(survived[sex =="male"])*100
female=np.mean(survived[sex =="female"])*100
print(male,female)

18.890814558058924 74.03846153846155

In [28]:
#33
ages = df["Age"].to_numpy()
male_age = np.mean(ages[sex == "male"])
female_age = np.mean(ages[sex == "female"])
print(male_age,female_age)

30.14067590987868 27.78846153846154

In [29]:
#34
male_sur=np.mean(ages[(sex=="male")&(survived == 1)])
male_notsur=np.mean(ages[(sex=="male")&(survived==0)])
female_sur=np.mean(ages[(sex=="female")&(survived==1)])
female_notsur=np.mean(ages[(sex =="female")&(survived==0)])
print(male_sur,male_notsur,female_sur,female_notsur)

27.382293577981653 30.78311965811966 28.532467532467532 25.666666666666668

In [45]:
#35
fares = df['Fare'].to_numpy()
print(np.min(fares),np.max(fares),np.mean(fares))

0.0 512.3292 32.09668087739032

In [46]:
#36
np.std(ages).tolist()

12.977627127265219

In [32]:
comparison = pd.DataFrame({
    "Показатель": [
        "Общий процент выживших",
        "Процент выживших мужчин",
        "Процент выживших женщин",
        "Средний возраст мужчин",
        "Средний возраст женщин",
        "Средний возраст выживших мужчин",
        "Средний возраст погибших мужчин",
        "Средний возраст выживших женщин",
        "Средний возраст погибших женщин",
        "Минимальная стоимость билета",
        "Максимальная стоимость билета",
        "Средняя стоимость билета",
        "Стандартное отклонение возраста"
    ],
    "Значение": [
        np.mean(survived) * 100,
        male,
        female,
        male_age,
        female_age,
        male_sur,
        male_notsur,
        female_sur,
        female_notsur,
        np.nanmin(fares),
        np.nanmax(fares),
        np.nanmean(fares),
        np.std(ages, ddof=1)
    ]
})

comparison

                         Показатель    Значение
0            Общий процент выживших   38.245219
1           Процент выживших мужчин   18.890815
2           Процент выживших женщин   74.038462
3            Средний возраст мужчин   30.140676
4            Средний возраст женщин   27.788462
5   Средний возраст выживших мужчин   27.382294
6   Средний возраст погибших мужчин   30.783120
7   Средний возраст выживших женщин   28.532468
8   Средний возраст погибших женщин   25.666667
9      Минимальная стоимость билета    0.000000
10    Максимальная стоимость билета  512.329200
11         Средняя стоимость билета   32.096681
12  Стандартное отклонение возраста   12.984932

контрольный вопрос:большая часть мужчин погибла, а большая часть женщин выжила

In [33]:
#V1
result_1 = df[
    (df["Sex"] == "male")
    & (df["Age"] > 30)
    & (df["Pclass"] == 1)
]
print(len(result_1))
result_1.head(10)

75

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,C
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,C
110,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,S
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,S
137,138,0,1,"Futrelle, Mr. Jacques Heath",male,37.0,1,0,113803,53.1000,S

In [34]:
#V2
result_2 = df[
    ((df['Age']<18)
    |(df['Sex']=='female'))
    &(df['Survived']==1)
]
print(len(result_2))

254

In [35]:
#V3
sred3=df.loc[df['Pclass']==3,'Fare'].mean()
result_3 = df[
    (df['Pclass']==3)
    &(df['Fare']>sred3)
]
result_3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,Q
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,S
...,...,...,...,...,...,...,...,...,...,...,...
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,C
860,861,0,3,"Hansen, Mr. Claus Peter",male,41.0,2,0,350026,14.1083,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,28.0,8,2,CA. 2343,69.5500,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,Q
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S

In [36]:
#V4
result_4 = df[
    (df['Age']>=20)
    &(df['Age']<=40)
    &(df['Embarked']=="S")
]
result_4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S

Контрольный вопрос: И означает выполнение всех условий одновременно, ИЛИ — выполнение хотя бы одного.

In [37]:
#37
titanic_statistics = df.groupby(
    ["Pclass", "Sex"],
    as_index=False
).agg(
    PassengerCount=("PassengerId", "size"),
    MeanAge=("Age", "mean"),
    SurvivalPercent=("Survived", lambda x: x.mean() * 100),
    MeanFare=("Fare", "mean")
)

titanic_statistics

   Pclass     Sex  PassengerCount    MeanAge  SurvivalPercent    MeanFare
0       1  female              92  33.630435        96.739130  106.693750
1       1    male             122  38.995246        36.885246   67.226127
2       2  female              76  28.703947        92.105263   21.970121
3       2    male             108  30.512315        15.740741   19.741782
4       3  female             144  23.572917        50.000000   16.118810
5       3    male             347  26.911873        13.544669   12.661633

In [38]:
#38
titanic_statistic = df.groupby(
    ['Embarked'],
    as_index=False,
).agg(
    PassengerCount=("PassengerId", "size"),
    SurvivalPercent=("Survived", lambda x: x.mean() * 100),
)
titanic_statistic

  Embarked  PassengerCount  SurvivalPercent
0        C             168        55.357143
1        Q              77        38.961039
2        S             644        33.695652

In [39]:
#39
class_survival = df.groupby("Pclass")["Survived"].mean() * 100
class_survival[
    class_survival == class_survival.max()
]

Pclass
1    62.616822
Name: Survived, dtype: float64

Контрольный вопрос: фильтрация выбирает отдельные строки, а группировка объединяет строки по признакам для расчёта общих показателей.

In [40]:
#40
df.to_csv(
    "titanic_processed.csv",
    index=False,
    encoding="utf-8-sig"
)

In [41]:
#41
titanic_statistics.to_csv(
    "titanic_statistics.csv",
    index=False,
    encoding="utf-8-sig"
)

In [47]:
#42
loaded_df = pd.read_csv("titanic_processed.csv")
pd.testing.assert_frame_equal(
    df.reset_index(drop=True),
    loaded_df,
    check_exact=False,
    rtol=1e-12,
    atol=1e-12
)

loaded_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

43. Какие признаки содержали больше всего пропусков?
Больше всего пропусков было в Cabin и в Age.
44. После обработки осталось 889 строк и 11 столбцов вместо 891 строки и 12 столбцов. Заполнение возраста медианой уменьшило стандартное отклонение и изменило среднее.
45. Как различалась выживаемость мужчин и женщин?
В обработанном наборе выживаемость женщин составила примерно 74,04%, мужчин — 18,89%.
46. В каком классе была наибольшая доля выживших?
В первом классе — примерно 62,62% после обработки.
47. Какие возможности Pandas и NumPy были полезны?
Pandas — загрузка таблиц, обработка пропусков, фильтрация, группировка и сохранение CSV. NumPy — вычисление средних, процентов, минимумов, максимумов и стандартного отклонения.

In [43]:
#выводы прописаны в пунктах 43-47, ниже представлена таблица сравнения возрастов до заполнения и после
comparison = pd.DataFrame({
    "До заполнения": stat_before.iloc[0],
    "После заполнения": stat_after.iloc[0]
})
comparison

                        До заполнения  После заполнения
Среднее                     29.699118         29.361582
Медиана                     28.000000         28.000000
Минимум                      0.420000          0.420000
Максимум                    80.000000         80.000000
Стандартное отклонение      14.526497         13.019697
Количество значений        714.000000        891.000000